#!/usr/bin/python3

import os
import util
import getopt
import sys
import importlib

available_modules = {
    "dash_parser": True,
    "monitoring": True,
    "sensors": True,
    "sms_server": "sms",
    "sms_client": "sms",
    "unify": True,
    "ups": True,
    "notifier": True
}

if len(sys.argv) > 1 and sys.argv[1] in available_modules:
    util.import_env()

    if available_modules[sys.argv[1]] != True:
        module = available_modules[sys.argv[1]]
    else:
        module = sys.argv[1]

    try:
        module = importlib.import_module("modules.%s.%s" % (module, sys.argv[1]))
        module.main()
    except Exception as e:
        util.prnt("[%s] global failure: %s" % (module, str(e)), util.LOG_ERR)
else:
    print("Usage: dio cmd [flags]")